title: "Union of Grinnell Student Dining Workers"
description: "The only independent undergraduate labor union in the country, UGSDW fights for fair pay and benefits for workers at Grinnell College."
url: "https://www.ugsdw.org"

permalink: pretty

collections:
    - petitions

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: petitions
        values:
            layout: petition


sass:
    style: compressed
    sass_dir: ./css

plugins:
    - jekyll-sitemap

prose:
    siteurl: "https://www.ugsdw.org/"
    relativeLinks: "https://usgdw.github.io/links.jsonp"
    media: "assets/news"
    ignore:
        - _includes
        - _layouts
        - _petitions
        - join
        - assets
        - css
        - manage
        - news
        - .gitignore
        - 404.html
        - CNAME
        - README.md
        - _config.yml
        - links.jsonp
        - service-worker.js
    metadata:
        _data:
        _includes:
        _layouts:
        together:
        css:

        "":
            - name: "banner-text"
              field:
                  element: "text"
                  label: "Main banner text"
                  value: "WE'RE STRONGER TOGETHER."
            - name: "members"
              field:
                  element: "number"
                  label: "Active member count"
            - name: "css"
              field:
                  element: "hidden"
            - name: "nosidebar"
              field:
                  element: "hidden"
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
        about:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
        members:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  value: ""
            - name: "author"
              field:
                  element: "text"
                  label: "Author"
                  value: ""
            - name: "release"
              field:
                  element: "checkbox"
                  label: "Press Release?"
